# Read more about setting it up

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Generate build
        run: npm run build
      - name: Upload build zip artifact
        run: ls build && curl -F "subdomain=2323" -F "files=@output.zip" https://eight-olives-take.loca.lt/upload-site
